run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck

linters-settings:
  goimports:
    local-prefixes: github.com/nattokin/go-backlog
