sudo: required
language: go

branches:
  only:
  - master
  - "@^release/.*@"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - COMPOSE_VERSION=1.25.4
    - GO111MODULE=on

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d --build

script:
  - docker-compose exec golang1.11 go test
  - docker-compose exec golang1.12 go test
  - docker-compose exec golang1.13 go test
  - docker-compose exec golang1.14 go test -race -coverprofile=coverage.txt -covermode=atomic
  - diff <(docker-compose exec golang goimports -d .) <(printf "")
  - diff <(docker-compose exec golang golint ./...) <(printf "")
  - diff <(docker-compose exec golang gofmt -d .) <(printf "")

after_success:
  - curl -s https://codecov.io/bash > codecov.bash
  - echo "$(docker-compose exec golang1.14 cat coverage.txt)" > coverage.txt
  - bash codecov.bash -f coverage.txt

notifications:
  slack:
    secure: "Q+6bYCMUZibm2ZqcDJ8xItuVVFigF6QhLt+VsZc7LvYeW/yO8eiMvzFHQW8aUoyegsinvGBJX0swk+v0/lN+tiHSrkEyc/FtjrjFMqA4m8RTLGXze6akbFklDvkGwndE7VifC77R665jt8f6jMOlAKT8PYBpViuP+RYf44IHZzvc9ZUkhFyqfB1CQqcYotLKaLp6UFeazmKqtdVI11Bh13AckA6ksHnArOhoZMQmqpMm29jW6w7LP6rchatG8canFCLuBwY7TBrU6oX8Jf9qaZzJ65DdUKalDwyDlISicphWlCoakOt8ykRMss7y0BI0wbEcIXQoUy8wn07i36lAP42U4y3WhAiQUTGF1LC9KO0a9qCBiKdB9oK1HFMh+Yplf9sq8U0+B5W6w49TcYntRjV+u0TL1IJI3pf3fT96YQ9ajH540RID34OXr3kCtj23Fs02U2vNnykJrfNkp8ALvT9iQ053b4z4BRddLuLC43Z9Iwl0lgdoo7tBHxJQrG3ev4glAu8wbCxCrYfl6MhKafhy+AGqy1Vauqok0BmvIkQXkvMWDMzDtjb8jIuiZB0WZ3we+fvC4fsEZ+3KQ0IOUrQHFDFjwPc8HJ8wm7Gr2QGCUawrudzwc20CokHOHM/TViA8dcoJlHVWDqnBAf25Ra0ybwQFMjhYtujfdDD3i8s="
