sudo: required
services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose up -d --build
  - docker-compose exec golang go test -coverprofile=coverage.txt -cover -v ./

after_success:
  - docker-compose exec golang goveralls -coverprofile=coverage.txt -covermode=count -service=travis-ci -repotoken $COVERALLS_TOKEN

env:
  global:
    - COMPOSE_VERSION: 1.25.4
    - secure: "ps0Z4HQMBn1a6ZjnzMhM3VAJYr2vsrBih/aiWkrrZlpjgwecybsf1Aurp9nnLfDub80W0FMlwrbBV43nS7lRdm5RGS+FM7p8xlyPLU0C6FEBSiQbAbIkHeEQ4xRJ4h7ECIr5fwtj2H8+Khtc9kV/AWGbnPhATddr30TlFbwADff8umbi6kmzuGOJmrNRRhKOSEtvDAkyGBH2wpERjdALNwCv+ICfenK7FzKMwD2rWQJ01SDd5CCnDNo2ATMsfUr1LtvMvIkR9yXDOC40YacsnBBor2QJ/zioSR87IN42v7/91LKpCm70sLZz5xU7XN0NcBJes75MY7JzpOxbpXi1sOExnmjf0PfXpsfufGF350OMq68fE6DrHNQxDpXoRiXvcpEqdtXiKu2JbsQM6kP2iV1sA8ps7BKy0t/t1NZV5Q335vBk0RReSnYlJN6DPfcy5hQoSkK2KzAoKUjJOz5YEFwpJuyj0vSoRdrkxbyZQrnDa/Yu6VHutptcST3EMP5cZS8apu87yTvb0bTGuSpZsUsrv1FzaIRrKnu+rZ/wPggShg3k2cWoIdX95AIISVQDW7wiWCwlUXvCirOVTvdonchPRNZ69Xm7JyzJwVfxBdodgQHSHDr3MTf67pX/cxxYiDFtn/O7SpQp/m1XKJ5ggEz5HSxvScQmrsny5H1Do9M="
