sudo: required
language: go
services:
  - docker

env:
  global:
    - COMPOSE_VERSION=1.25.4

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up -d --build

script:
  - docker-compose exec golang1.11 go test
  - docker-compose exec golang1.12 go test
  - docker-compose exec golang1.13 go test
  - docker-compose exec golang1.14 go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - curl -s https://codecov.io/bash > codecov.bash
  - docker-compose exec golang1.14 cat coverage.txt > coverage.txt
  - bash codecov.bash -f coverage.txt
