[changelog]
header = ""
body = """
## What's Changed
{% set breaking_commits = commits | filter(attribute="breaking", value=true) %}\
{% if breaking_commits %}
### ⚠️ Breaking Changes
{% for commit in breaking_commits %}\
- {{ commit.breaking_description | default(value=commit.message) | upper_first }}
{% endfor %}
{% endif %}\
{% for group, commits in commits | group_by(attribute="group") %}\
{% if group != "⚠️ Breaking Changes" %}
### {{ group }}
{% for commit in commits %}\
- {{ commit.message | upper_first }}\
{% if commit.breaking %} **(BREAKING)**{% endif %}

{% endfor %}
{% endif %}\
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
commit_parsers = [
  { message = "^feat!", group = "✨ Features" },
  { message = "^fix!", group = "🐛 Bug Fixes" },
  { message = "^refactor!", group = "🔨 Refactoring" },
  { message = "^feat", group = "✨ Features" },
  { message = "^fix", group = "🐛 Bug Fixes" },
  { message = "^refactor", group = "🔨 Refactoring" },
  { message = "^docs", group = "📚 Documentation" },
  { message = "^ci", group = "⚙️ CI" },
  { message = "^chore", group = "🧹 Chores" },
  { message = ".*", skip = true },
]
filter_commits = true
tag_pattern = "v[0-9]+\\.[0-9]+\\.[0-9]+"
