codecov:
  strict_yaml_branch: "master"
  max_report_age: 24
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "80...100"
  status:
    project: on
    patch: off
  notify:
    slack:
      default:
        url: secret:y/1ITSom9yLhw8dxCilpBQvo1HdNN0XiNhshDuB0vW7353LoFtQloQGEdkjPUwae8DT7fgxzCLXPfdUdjaJ7jLx3jQgz/wXguQn7to9fDW/loQEAsUh9l+IWFc0mCZoFKyxOucnLNuR7mQxkawaajPZhp7GcMfgcM2aNT5qa4P8=

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches:
    - master

ignore:
  - "./docker"
  - "./exxamples"
  - "./testdata"

github_checks:
  annotations: true
