version: '3'
services:
  golang:
    container_name: golang_container
    build: ./docker/golang
    tty: true
    environment:
      - GO111MODULE=on
    volumes:
      - ./:/go/src/github.com/nattokin/go-backlog
    working_dir: /go/src/github.com/nattokin/go-backlog

