name: Check Breaking Change Consistency

on:
  pull_request_target:
    types: [opened, edited, labeled, unlabeled]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check breaking change consistency
        run: node .github/scripts/check-breaking-change.js
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
