name: Check Breaking Change Consistency

on:
  pull_request_target:
    types: [opened, edited, labeled, unlabeled]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Check breaking change consistency
        run: node .github/scripts/check-breaking-change.js
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_LABELS: ${{ toJson(github.event.pull_request.labels.*.name) }}
