name: GoReport

on:
  push:
    branches: [ main ]

jobs:

  go_report:
    name: Refresh go report
    runs-on: ubuntu-latest
    steps:

    - uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9 # v1.0
